### ISSUE TITLE
Use `panel.plugin({use: VueNestable})`

### ISSUE THREAD

**Issue by distantnative** [chrisbeluga/kirby-navigation#11]
Instead using this `beforeCreate` hook https://github.com/chrisbeluga/kirby-navigation/blob/main/src/app.vue#L329

you should be able to achieve the same in your https://github.com/chrisbeluga/kirby-navigation/blob/main/src/index.js via

```js
panel.plugin('beluga/navigation', {
    fields:  ...,
    use: VueNestable
})
```

**Comment by chrisbeluga** [comment]
@distantnative Thanks for the heads up, updated with latest commit
