### ISSUE TITLE
Relative Links and Multi Lang Menus

### ISSUE THREAD

**Issue by marcus-at-localhost** [chrisbeluga/kirby-navigation#16]
I prepared my menu locally with a different domain and ended up with non working links after deploying.

I tried to solve it in my template something like this: `$navigation->id() ?? $navigation->url()` but for external links id() is an index number, so that's not working. (I guess one could test against the current host)

Is there a better way to work around that? 

And how to handle multi lang menus? Building two?

**Comment by chrisbeluga** [comment]
This will be fixed in the next release :)

**Comment by Maybach91** [comment]
@chrisbeluga Do you have any timeframe for the next release? :)

**Comment by sachbearbeiter** [comment]
This has been fixed in the v4 release.
