### ISSUE TITLE
Use page id on Kirby links instead absolute url

### ISSUE THREAD

**Issue by afbora** [chrisbeluga/kirby-navigation#21]
It doesn't make sense for internal page links to have absolute url. Links working in local will be broken when you deploy prod.

**Comment by afbora** [comment]
@chrisbeluga Can you add that to the big change please? 🙏

**Comment by chrisbeluga** [comment]
yep, will definitely include this!

**Comment by eXpl0it3r** [comment]
Any updates on this? I'm unfortunately not very well versed in Vue to provide a PR.

**Comment by MaPhiKo** [comment]
I recently tried to use the Plugin and ran into the issue described in the op, where deployment breaks all links.
Is there any update on this?

**Comment by sachbearbeiter** [comment]
This has been fixed in the v4 release.
