### ISSUE TITLE
Make open/close more easy Double click to open and close menu item

### ISSUE THREAD

**Issue by REHvision** [chrisbeluga/kirby-navigation#22]
Thank you for the great plugin, it already helped a lot with menu building and replaced my previous setup using structure fields nested inside structure fields :heart: 

It might be on purpose that the label is not edible inline and expanded only by click in menu (three dots + edit).
But actually it is very cumbersome to edit multiple menu entries this way.

**Please consider the following suggestions:**
1) Add double click to open and close the menu item again (still two clicks but without mouse movement in between)
2) Move the "edit" button out of the options dropdown menus directly into the menu item head next to the three dots (only one instead of two clicks)
3) Leave duplicate and delete in the options dropdown and remove the bottom bar when toggled open completely

Also I wanted to note that the open and close icons are misleading in my opinion (looks like **add** and **delete** when considering the icon usage in other aspects of Kirby)
So I would suggest to use `pencil` icon to edit/open + `check` for closing or toggle the `up` / `down` icons in the bar (like in most accordions)

![Bildschirmfoto von 2021-11-02 16-11-52](https://user-images.githubusercontent.com/2584674/139875649-2229dd4a-2ff3-4357-9dfb-ca37eee09891.png)

**Comment by sachbearbeiter** [comment]
This has been hopefully fixed in the v4 release (if I have misunderstood something, please open a new ticket).
