### ISSUE TITLE
Navigation Items appear blank with Kirby 3.6

### ISSUE THREAD

**Issue by fat-buddha-designs** [chrisbeluga/kirby-navigation#23]
Hi 
I have been using your navigation plugin with Kirby 3.5 and it works perfectly.
I'm just trying it out with Kirby 3.6 and I get no titles or no ability to edit each navigation item, as per the attached image.
Is there anything I need to do to get this working again?
![kirby-navigation-plugin](https://user-images.githubusercontent.com/74487846/144296756-55489173-828c-4259-9b45-72b34cc8382a.jpg)

Many Thanks

**Comment by chrisbeluga** [comment]
There is a kirby 3.6 specific release as this brought about a number of breaking changes.

You can find it [here](https://github.com/chrisbeluga/kirby-navigation/releases/tag/2.0.0)

**Comment by fat-buddha-designs** [comment]
Great, thank you.
