### ISSUE TITLE
Plugin is not working with kirby 3.6

### ISSUE THREAD

**Issue by nicbent** [chrisbeluga/kirby-navigation#24]

**Comment by nicbent** [comment]
You always get an empty element. Tried it out on a fresh starterkit installation. On Kirby 3.5.8 the plugin is running as expected..

![gh](https://user-images.githubusercontent.com/33845351/147359433-b4cbf986-8641-432c-bd41-1933c8afef96.png)

**Comment by chrisbeluga** [comment]
There is two versions of the plugin available. One is for kirby versions
less than 3.6 and another for 3.6.

It's in the releases section which can be found here

https://github.com/chrisbeluga/kirby-navigation/releases/tag/2.0.0

Let me know if you have any further issues.

**Comment by eXpl0it3r** [comment]
Might be a good hint to add to the readme on the `main` branch and/or swap the branches 🙂
