### ISSUE TITLE
Does it support different menus in different languages?

### ISSUE THREAD

**Issue by maxyahontov** [chrisbeluga/kirby-navigation#25]
I need to create navigation that depends from the site language. Now this plugin saves same data in all language versions. Could you please fix this?

**Comment by sebert007** [comment]
Same with me. Looking at the code, it seems there is a multi-language implementation, but it doesn't seem to work. It overwrites the languages files and seems to be capable to only hold one translation.

Any idea how to fix this?

**Comment by sachbearbeiter** [comment]
This should be solved in the 4 version.
