### ISSUE TITLE
Highlight active menu item

### ISSUE THREAD

**Issue by LordCanis** [chrisbeluga/kirby-navigation#28]
Hey,

thanks for the awesome plugin.
Is it possible to highlight the active menu item?

I use:

    
    <?php foreach($site->navigation()->toStructure() as $navigation): ?>
      <li>
        <a <?php e($navigation->isOpen(), 'aria-current') ?> id="<?php echo $navigation->id() ?>"  href="<?php echo $navigation->url(); ?>" <?php echo $navigation->popup()->toBool() ? 'rel="noopener noreferrer" target="_blank"' : '' ?>>
      <?php echo $navigation->text() ?>
        </a>
      </li>
     <?php endforeach ?>
    
and insert in the a-Tag this

    <?php e($navigation->isOpen(), 'aria-current') ?>

Than all items are highlighted.
What am I doing wrong?

Thanks for your help!

**Comment by Sean-OShea** [comment]
@LordCanis felt on the same issue, a workaround was given in this issue #18 in the last comment.

**Comment by sachbearbeiter** [comment]
This should be solved in the 4 version. If something should be re-implemented in version 3, please create a new ticket.

**Comment by jhercher** [comment]
Yep, it works with Kirby 4.7 and v.4.1.1 of the navigation plugin. 

A note on: 
> `<?php e($navigation->isOpen(), 'aria-current') ?>`
> Than all items are highlighted.
> What am I doing wrong?

I had to use  `<?php e($navigation->isOpen()->value(), 'aria-current') ?>`

Another idea: The parent nav-items could also have the isOpen: true, if a child is open. My workaround is to check it with:
`class="<?php e(str_contains(kirby()->url('current'), $item->url()->value()), 'active') ?>">`

Great Plugin, thx!

**Comment by sachbearbeiter** [comment]
Thank you for your message.
The 4.1.2 version of the plugin contains both isOpen() and
isChildOpen(), and the following sentence was added to the README.md:

"As you can see, $item->isOpen()->value() can be used in this foreach()
to check whether the given menu item is the current page, and
$item->isChildOpen()->value() can be used to check whether any of the
child menu items is the current page."
