### ISSUE TITLE
Kirby 3.7 issue

### ISSUE THREAD

**Issue by ieteo** [chrisbeluga/kirby-navigation#30]
Kirby version:  **3.7.0.1**
kirby-navigation version: **2.1.2** 

This plug-in seem to have a Kirby 3.7 issue. When adding new "Kirby Link" item, the page selection modal is blank

![Screenshot 2022-06-30 121112](https://user-images.githubusercontent.com/98889739/176653189-eb60a0c3-5842-407b-b74b-ec53911b00d9.png)

No errors in browser console (Microsoft Edge and Firefox) nor in Kirby logs

**Comment by Messa1** [comment]
same on my local installation - 3.7.0.2
