### ISSUE TITLE
UI/UX Improvement Suggestion

### ISSUE THREAD

**Issue by manuelmoreale** [chrisbeluga/kirby-navigation#33]
The current implementation for the details modal has this footer right here with the remove button on the bottom right which is where kirby usually has the button to confirm the changes.

![Screenshot 2022-08-01 at 10 46 35 AM](https://user-images.githubusercontent.com/1738077/182110637-e9c9d714-a855-4fb8-8827-2da494066063.png)
 
Since this is similar in spirit to the structure form I'd suggest you implement something more similar to the footer for the structure field entry so confirm button on the bottom right and a discard changes to the left. This is because muscle memory inside the panel makes it so that you immediately go in the bottom right to confirm the changes.

![Screenshot 2022-08-01 at 10 47 45 AM](https://user-images.githubusercontent.com/1738077/182110937-2eda6c23-ad41-4414-bd74-4a53eefa19ad.png)

The delete action is already present in the dropdown menu so I don't think it is necessary to have it in the edit modal.

![Screenshot 2022-08-01 at 10 46 45 AM](https://user-images.githubusercontent.com/1738077/182110989-85a14a1a-a4c1-4c21-aac4-f6d38b3d9d16.png)

**Comment by sachbearbeiter** [comment]
This should be solved in the 4 version.
