### ISSUE TITLE
3.6 compatibility

### ISSUE THREAD

**Issue by afbora** [chrisbeluga/kirby-navigation#7]
![screen-capture-1156-Site - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/133127383-9ddff65a-bc2e-4c20-8f9c-470647bc7e82.png)

**Comment by chrisbeluga** [comment]
Will take a look at Kirby 3.6 and push a fix for this ASAP, I think by removing the k-list-item altogether would be beneficial
