### ISSUE TITLE
Install via Composer

### ISSUE THREAD

**Issue by TimGr** [chrisbeluga/kirby-navigation#8]
Hi,

do you plan to publish it as an composer package?
Would be awesome and much easier to install/update.

Thank your for your work. 
This is a super helpful plugin.

**Comment by chrisbeluga** [comment]
Hi @TimGr, 

Yeah, composer support is coming very soon!

**Comment by MaluNoPeleke** [comment]
Great news. As navigation is so common on all kinds of web projects I would even consider this plugin as part of the Kirby core experience once it will be a little bit more mature.

**Comment by chrisbeluga** [comment]
Composer support added in release [1.1.2](https://github.com/chrisbeluga/kirby-navigation/releases/tag/1.1.2)
